version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  flask:
    build: .
    ports:
      - "80:80"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""  # if you don't use password, leave empty
    depends_on:
      - redis
