services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
    command: --requirepass bipmpass
  web:
    build: .
    stop_signal: SIGINT
    ports:
      - '4000:80'
    volumes:
      - ./app:/app
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=bipmpass
      - REDIS_HOST=${REDIS_HOST}